<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bed_and_environment_mannequin">
<xacro:property name="body_len" value="1.75" />
<xacro:property name="comp_len" value="1.755" />
<xacro:property name="torso_thickness" value="${body_len/comp_len*0.18}" />
<xacro:property name="leg_thickness" value="${body_len/comp_len*0.16}" />
<xacro:property name="rotated_torso" value="${0.35-clavicle_len}" />
<xacro:property name="missing_neck_len" value="${0.05761}" />
<xacro:property name="missing_neck_width" value="${0.155}" />
<xacro:property name="missing_neck_thickness" value="${0.11}" />
<xacro:property name="clavicle_len" value="${body_len/comp_len*0.053}" />
<xacro:property name="torso_len" value="${body_len/comp_len*0.460}" />
<xacro:property name="leg_len" value="${body_len/comp_len*0.927}" />
<xacro:property name="thigh_len" value="${body_len/comp_len*0.927}" />
<xacro:property name="shank_len" value="${body_len/comp_len*0.927}" />
<xacro:property name="leg_len" value="${body_len/comp_len*0.927}" />
<xacro:property name="upper_arm_len" value="${body_len/comp_len*0.279}" />
<xacro:property name="fore_arm_len" value="${body_len/comp_len*0.257}" />
<xacro:property name="hand_len" value="${body_len/comp_len*0.190}" />
<xacro:property name="upper_arm_radius" value="${body_len/comp_len*0.053}" />
<xacro:property name="fore_arm_radius" value="${body_len/comp_len*0.033}" />
<xacro:property name="chest_width" value="${body_len/comp_len*0.310}" />
<xacro:property name="shoulder_width" value="${body_len/comp_len*0.465}" />
<xacro:property name="hip_width" value="${body_len/comp_len*0.361}" />
<xacro:property name="inter_leg_width" value="${body_len/comp_len*0.178}" />
<xacro:property name="thigh_len" value="${body_len/comp_len*0.424}" />
<xacro:property name="shank_len" value="${body_len/comp_len*0.422}" />
<!--<xacro:property name="torso_len" value="0.6" />-->
<!--<xacro:property name="leg_len" value="1.1" />-->

<!--<robot-->
  <!--name="bed_and_environment_mannequin">-->
  <link
   name="autobed/base_link">
    <inertial>
      <origin
        xyz="1.1357 5.02524375187963E-16 0.0837923121940762"
        rpy="0 0 0" />
      <mass
        value="6.1860172808288" />
      <inertia
        ixx="1.21978721906848"
        ixy="2.44249065417534E-15"
        ixz="-1.95644145492449E-15"
        iyy="8.04681346721547"
        iyz="-8.29396064187448E-16"
        izz="9.14286094259782" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/base_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/base_link.STL" />
      </geometry>
    </collision>
  </link>
    <link
   name="autobed/wall_link">
<inertial>
      <origin
        xyz="1.87797370531369 0.344853002331874 0.50260600946241"
        rpy="0 0 0" />
      <mass
        value="3357.24028579199" />
      <inertia
        ixx="6116.11427029265"
        ixy="3215.70073716445"
        ixz="-7.36787327233699"
        iyy="7061.83554462804"
        iyz="404.207480292852"
        izz="12009.0931540893" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/wall_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/wall_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
   name="autobed/origin_wall_joint"
    type="fixed">
    <origin
      xyz="-0.07 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/base_link" />
    <child
      link="autobed/wall_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <link
   name="autobed/bed_frame_link">
    <inertial>
      <origin
        xyz="1.21628575112374 -0.00457131635492439 -0.0135493327987712"
        rpy="0 0 0" />
      <mass
        value="438.573663325781" />
      <inertia
        ixx="42.8905274768398"
        ixy="0.0492397267886641"
        ixz="-5.59060599846785"
        iyy="241.766114116497"
        iyz="0.273352447936363"
        izz="273.415411937571" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/bed_frame_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/bed_frame_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
   name="autobed/tele_legs_joint"
    type="prismatic">
    <origin
      xyz="-0.0400000000000005 0 0.320000000000001"
      rpy="0 0 0" />
    <parent
      link="autobed/base_link" />
    <child
      link="autobed/bed_frame_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-1"
      upper="1"
      effort="0"
      velocity="0" />
  </joint>
  <link
   name="autobed/leg_rest_upper">
    <inertial>
      <origin
        xyz="0.200000000000001 0.105 5.39949211906603E-16"
        rpy="0 0 0" />
      <mass
        value="83.5800000000001" />
      <inertia
        ixx="7.20268062500001"
        ixy="6.22789394401658E-17"
        ixz="5.26123900305408E-16"
        iyy="8.00992412500002"
        iyz="-4.24421100017485E-15"
        izz="1.4215565" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/leg_rest_upper.STL" />
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/leg_rest_upper.STL" />
      </geometry>
    </collision>
  </link>
  <joint
   name="autobed/leg_rest_upper_hinge"
    type="revolute">
    <origin
      xyz="1.145 0 0"
      rpy="1.5707963267949 -1.84377299293392E-16 7.65430446472183E-16" />
    <parent
      link="autobed/bed_frame_link" />
    <child
      link="autobed/leg_rest_upper" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
   name="autobed/leg_rest_lower">
    <inertial>
      <origin
        xyz="0.34 0.105 -5.47791833032667E-17"
        rpy="0 0 0" />
      <mass
        value="142.086" />
      <inertia
        ixx="12.2445570625"
        ixy="-5.16774213504574E-17"
        ixz="-2.28125300458666E-16"
        iyy="17.1974382125"
        iyz="4.5484254092282E-16"
        izz="5.99721325" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/leg_rest_lower.STL" />
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/leg_rest_lower.STL" />
      </geometry>
    </collision>
  </link>
  <joint
   name="autobed/leg_rest_lower_hinge"
    type="revolute">
    <origin
      xyz="0.400000000000001 0 0"
      rpy="8.46545056276682E-16 -2.4743657509036E-16 -1.8315782125782E-16" />
    <parent
      link="autobed/leg_rest_upper" />
    <child
      link="autobed/leg_rest_lower" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
   name="autobed/head_rest_link">
    <inertial>
      <origin
        xyz="0.329573377413269 -0.160120828020686 0.144918621186554"
        rpy="0 0 0" />
      <mass
        value="224.783329311116" />
      <inertia
        ixx="32.8876282309991"
        ixy="1.69548410687658"
        ixz="-3.19639748968515"
        iyy="37.6526299034377"
        iyz="-6.40258778692133"
        izz="16.0712822442492" />
    </inertial>
    <visual>
      <origin
        xyz="0 ${0.21-0.04} 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/head_rest_link.STL" />
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 ${0.21-0.04} 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/head_rest_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
   name="autobed/head_rest_hinge"
    type="revolute">
    <origin
      xyz="0.835 0 ${0.04}"
      rpy="1.5708 0 -3.1416" />
    <parent
      link="autobed/bed_frame_link" />
    <child
      link="autobed/head_rest_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_rotated_to_worldframe_link">
  </link>
  <joint
    name="autobed/headrest_bed_to_worldframe_joint"
    type="revolute">
    <origin
      xyz="${rotated_torso+clavicle_len} ${0.15+0.21-0.12} 0"
      rpy="0. 0. 0." />
    <!--<origin-->
      <!--xyz="0.40949 0.05 0"-->
      <!--rpy="0. 0. 0." />-->
    <parent
      link="autobed/head_rest_link" />
    <child
      link="autobed/neck_rotated_to_worldframe_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_updown_worldframe_translation_link">
  </link>
  <joint
    name="autobed/bed_neck_worldframe_updown_joint"
    type="prismatic">
    <origin
      xyz="0.0 0.0 0"
      rpy="0.0 0.0 0.0" />
    <parent
      link="autobed/neck_rotated_to_worldframe_link" />
    <child
      link="autobed/neck_updown_worldframe_translation_link" />
    <axis
      xyz="-1 0 0" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_rotated_to_bedframe_link">
  </link>
  <joint
    name="autobed/bed_neck_to_bedframe_joint"
    type="revolute">
    <origin
      xyz="0.0 0.0 0"
      rpy="0. 0. 0." />
    <parent
      link="autobed/neck_updown_worldframe_translation_link" />
    <child
      link="autobed/neck_rotated_to_bedframe_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_updown_bedframe_translation_link">
  </link>
  <joint
    name="autobed/bed_neck_base_updown_bedframe_joint"
    type="prismatic">
    <origin
      xyz="0.0 0.0 0"
      rpy="0. 0. 0." />
    <parent
      link="autobed/neck_rotated_to_bedframe_link" />
    <child
      link="autobed/neck_updown_bedframe_translation_link" />
    <axis
      xyz="-1 0 0" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_base_link">
  </link>
  <joint
    name="autobed/bed_neck_base_leftright_joint"
    type="prismatic">
    <origin
      xyz="0 0 0"
      rpy="0 3.14159 0" />
    <parent
      link="autobed/neck_updown_bedframe_translation_link" />
    <child
      link="autobed/neck_base_link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_twist_link">
  </link>
  <joint
    name="autobed/neck_twist_joint"
    type="revolute">
    <origin
      xyz="0.0 0.0 0"
      rpy="0. 0. 0." />
    <parent
      link="autobed/neck_base_link" />
    <child
      link="autobed/neck_twist_link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_tilt_link">
  </link>
  <joint
    name="autobed/neck_tilt_joint"
    type="revolute">
    <origin
      xyz="0.0 0.0 0"
      rpy="0. 0. 0." />
    <parent
      link="autobed/neck_twist_link" />
    <child
      link="autobed/neck_tilt_link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/neck_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/neck_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/neck_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/neck_to_neck_top_joint"
    type="fixed">
    <origin
      xyz="-0.07239 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/neck_tilt_link" />
    <child
      link="autobed/neck_link" />
  </joint>
  <link
    name="autobed/neck_top_rotated_link">
  </link>
  <joint
    name="autobed/neck_rotation_fixed_joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="-1.570796 0 1.570796" />
    <parent
      link="autobed/neck_link" />
    <child
      link="autobed/neck_top_rotated_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/head_roty_link">
  </link>
  <joint
    name="autobed/neck_head_roty_joint"
    type="revolute">
    <origin
      xyz="0.0154 0 0.07779"
      rpy="0 0 0" />
    <parent
      link="autobed/neck_top_rotated_link" />
    <child
      link="autobed/head_roty_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/head_rotz_link">
  </link>
  <joint
    name="autobed/neck_head_rotz_joint"
    type="revolute">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/head_roty_link" />
    <child
      link="autobed/head_rotz_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>

  <link
    name="autobed/head_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/head_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/head_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/neck_head_rotx_joint"
    type="revolute">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/head_rotz_link" />
    <child
      link="autobed/head_link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-2"
      upper="2"
      effort="0"
      velocity="0" />
  </joint>
  <joint
    name="autobed/head_eyes_joint"
    type="fixed">
    <origin
      xyz="0.09779 0 0.03"
      rpy="0 0 0" />
    <parent
      link="autobed/head_link" />
    <child
      link="autobed/eyes_link" />
  </joint>
  <link
    name="autobed/eyes_link">
  </link>
  <joint
    name="autobed/neck_missing_neck_joint"
    type="fixed">
    <origin
      xyz="${missing_neck_len} 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/neck_base_link" />
    <child
      link="autobed/missing_neck_link" />
  </joint>
  <link
    name="autobed/missing_neck_link">
    <visual>
      <origin
        xyz="${-missing_neck_len/2.} 0.0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <box size="${missing_neck_len*4} ${missing_neck_thickness*2} ${missing_neck_width*2} "/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${-missing_neck_len/2.} 0.0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <box size="${missing_neck_len*4} ${missing_neck_thickness*2} ${missing_neck_width*2} "/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/neck_torso_box_joint"
    type="fixed">
    <origin
      xyz="${clavicle_len} 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/missing_neck_link" />
    <child
      link="autobed/torso_link" />
  </joint>
  <link
    name="autobed/torso_link">
    <visual>
      <origin
        xyz="${rotated_torso/2.} 0.0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <box size="${rotated_torso*2} ${torso_thickness*2} ${(chest_width-torso_thickness)*2} "/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${rotated_torso/2.} 0.0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <box size="${rotated_torso*2} ${torso_thickness*2} ${(chest_width-torso_thickness)*2} "/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/neck_torso_clavicle_joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/torso_link" />
    <child
      link="autobed/torso_clavicle_link" />
  </joint>
  <link
    name="autobed/torso_clavicle_link">
    <visual>
      <origin
        xyz="0 0.0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${shoulder_width}" radius="${clavicle_len}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0.0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${shoulder_width}" radius="${clavicle_len}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/torso_side_right_joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 1.5708 0" />
    <parent
      link="autobed/torso_link" />
    <child
      link="autobed/torso_side_right_link" />
  </joint>
  <link
    name="autobed/torso_side_right_link">
    <visual>
      <origin
        xyz="${chest_width/2 - torso_thickness/2} 0. ${rotated_torso/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${rotated_torso}" radius="${torso_thickness/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${chest_width/2 - torso_thickness/2} 0. ${rotated_torso/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${rotated_torso}" radius="${torso_thickness/2}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/torso_side_left_joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 1.5708 0" />
    <parent
      link="autobed/torso_link" />
    <child
      link="autobed/torso_side_left_link" />
  </joint>
  <link
    name="autobed/torso_side_left_link">
    <visual>
      <origin
        xyz="${-1*(chest_width/2 - torso_thickness/2)} 0. ${rotated_torso/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${rotated_torso}" radius="${torso_thickness/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${chest_width/2 - torso_thickness/2} 0. ${rotated_torso/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${rotated_torso}" radius="${torso_thickness/2}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/torso_pelvis_joint"
    type="revolute">
    <origin
      xyz="${rotated_torso} 0.0 0"
      rpy="0 0 0" />
    <parent
      link="autobed/torso_link" />
    <child
      link="autobed/pelvis_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/pelvis_link">
    <visual>
      <origin
        xyz="${(leg_len+torso_len-rotated_torso)/2.} 0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${1.2*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <box size="${(leg_len+torso_len-rotated_torso)*2} ${leg_thickness*2} ${(hip_width-leg_thickness)*2} "/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${(leg_len+torso_len-rotated_torso)/2.} 0 0"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${1.2*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <box size="${(leg_len+torso_len-rotated_torso)*2} ${leg_thickness*2} ${(hip_width-leg_thickness)*2} "/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/legs_side_right_joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 1.5708 0" />
    <parent
      link="autobed/pelvis_link" />
    <child
      link="autobed/legs_side_right_link" />
  </joint>
  <link
    name="autobed/legs_side_right_link">
    <visual>
      <origin
        xyz="${hip_width/2 - leg_thickness/2} 0. ${(leg_len+torso_len-rotated_torso)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${leg_len+torso_len-rotated_torso}" radius="${leg_thickness/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${hip_width/2 - leg_thickness/2} 0. ${(leg_len+torso_len-rotated_torso)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${rotated_torso}" radius="${torso_thickness/2}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/legs_side_left_joint"
    type="fixed">
    <origin
      xyz="0 0 0"
      rpy="0 1.5708 0" />
    <parent
      link="autobed/pelvis_link" />
    <child
      link="autobed/legs_side_left_link" />
  </joint>
  <link
    name="autobed/legs_side_left_link">
    <visual>
      <origin
        xyz="${-1*(hip_width/2 - leg_thickness/2)} 0. ${(leg_len+torso_len-rotated_torso)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${leg_len+torso_len-rotated_torso}" radius="${leg_thickness/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="${-1*(hip_width/2 - leg_thickness/2)} 0. ${(leg_len+torso_len-rotated_torso)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${rotated_torso}" radius="${torso_thickness/2}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/pelvis_knee_left_joint"
    type="fixed">
    <origin
      xyz="${thigh_len+torso_len-rotated_torso} 0 ${-1*inter_leg_width/2}"
      rpy="-1.5708 0 1.5708" />
    <parent
      link="autobed/pelvis_link" />
    <child
      link="autobed/knee_left_link" />
  </joint>
  <link
    name="autobed/knee_left_link">
  </link>
  <joint
    name="autobed/knee_foot_left_joint"
    type="fixed">
    <origin
      xyz="0 0 ${-1*shank_len}"
      rpy="0 0 0" />
    <parent
      link="autobed/knee_left_link" />
    <child
      link="autobed/foot_left_link" />
  </joint>
  <link
    name="autobed/foot_left_link">
  </link>
  <joint
    name="autobed/pelvis_knee_right_joint"
    type="fixed">
    <origin
      xyz="${thigh_len+torso_len-rotated_torso} 0 ${inter_leg_width/2}"
      rpy="-1.5708 0 1.5708" />
    <parent
      link="autobed/pelvis_link" />
    <child
      link="autobed/knee_right_link" />
  </joint>
  <link
    name="autobed/knee_right_link">
  </link>
  <joint
    name="autobed/knee_foot_right_joint"
    type="fixed">
    <origin
      xyz="0 0 ${-1*shank_len}"
      rpy="0 0 0" />
    <parent
      link="autobed/knee_right_link" />
    <child
      link="autobed/foot_right_link" />
  </joint>
  <link
    name="autobed/foot_right_link">
  </link>
  <joint
    name="autobed/torso_upper_arm_right_joint"
    type="revolute">
    <origin
      xyz="0 0 ${shoulder_width/2 - upper_arm_radius}"
      rpy="-1.5708 0 1.5708" />
    <parent
      link="autobed/torso_link" />
    <child
      link="autobed/upper_arm_right_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/upper_arm_right_link">
    <visual>
      <origin
        xyz="0 0. ${-1*upper_arm_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${upper_arm_len}" radius="${upper_arm_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0. ${-1*upper_arm_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${upper_arm_len}" radius="${upper_arm_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/upper_arm_fore_arm_right_joint"
    type="revolute">
    <origin
      xyz="0 0 ${-1*upper_arm_len}"
      rpy="0 0 0" />
    <parent
      link="autobed/upper_arm_right_link" />
    <child
      link="autobed/fore_arm_right_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/fore_arm_right_link">
    <visual>
      <origin
        xyz="0 0. ${-1*(fore_arm_len)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${fore_arm_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0. ${-1*fore_arm_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${fore_arm_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/fore_arm_hand_right_joint"
    type="revolute">
    <origin
      xyz="0 0 ${-1*fore_arm_len}"
      rpy="0 0 0" />
    <parent
      link="autobed/fore_arm_right_link" />
    <child
      link="autobed/hand_right_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/hand_right_link">
    <visual>
      <origin
        xyz="0 0. ${-1*(hand_len)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${hand_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0. ${-1*hand_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${hand_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/torso_upper_arm_left_joint"
    type="revolute">
    <origin
      xyz="0 0 ${-1.*(shoulder_width/2 - upper_arm_radius)}"
      rpy="-1.5708 0 1.5708" />
    <parent
      link="autobed/torso_link" />
    <child
      link="autobed/upper_arm_left_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/upper_arm_left_link">
    <visual>
      <origin
        xyz="0 0. ${-1*upper_arm_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${upper_arm_len}" radius="${upper_arm_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0. ${-1*upper_arm_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${upper_arm_len}" radius="${upper_arm_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/upper_arm_fore_arm_left_joint"
    type="revolute">
    <origin
      xyz="0 0 ${-1*upper_arm_len}"
      rpy="0 0 0" />
    <parent
      link="autobed/upper_arm_left_link" />
    <child
      link="autobed/fore_arm_left_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/fore_arm_left_link">
    <visual>
      <origin
        xyz="0 0. ${-1*(fore_arm_len)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${fore_arm_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0. ${-1*fore_arm_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${fore_arm_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="autobed/fore_arm_hand_left_joint"
    type="revolute">
    <origin
      xyz="0 0 ${-1*fore_arm_len}"
      rpy="0 0 0" />
    <parent
      link="autobed/fore_arm_left_link" />
    <child
      link="autobed/hand_left_link" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-3"
      upper="3"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="autobed/hand_left_link">
    <visual>
      <origin
        xyz="0 0. ${-1*(hand_len)/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.55*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2} "/>-->
        <cylinder length="${hand_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin
        xyz="0 0. ${-1*hand_len/2}"
        rpy="0 0 0" />
      <geometry>
        <!--<box size="0.5 0.5 .2"/>-->
        <!--<box size="${0.6*body_len/comp_len*2} 0.35 ${0.5*body_len/comp_len*2}"/>-->
        <cylinder length="${hand_len}" radius="${fore_arm_radius}"/>
      </geometry>
    </collision>
  </link>


  <!--<link-->
    <!--name="autobed/upper_body_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/upper_body_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/upper_body_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/neck_body_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.00 0 0"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/neck_base_link" />-->
    <!--<child-->
      <!--link="autobed/upper_body_link" />-->
    <!--<axis-->
      <!--xyz="0 0 -1" />-->
    <!--<limit-->
      <!--lower="-2"-->
      <!--upper="2"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/mid_body_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/mid_body_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/mid_body_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/upper_mid_body_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.35052 0 0"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/upper_body_link" />-->
    <!--<child-->
      <!--link="autobed/mid_body_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-2"-->
      <!--upper="2"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/lower_body_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/lower_body_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/lower_body_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/mid_lower_body_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.15113 0 0"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/mid_body_link" />-->
    <!--<child-->
      <!--link="autobed/lower_body_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-2"-->
      <!--upper="2"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/quad_left_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/quad_left_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/quad_left_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/body_quad_left_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.05207 0 -0.08636"-->
      <!--rpy="0 0 -.25" />-->
    <!--<parent-->
      <!--link="autobed/lower_body_link" />-->
    <!--<child-->
      <!--link="autobed/quad_left_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3."-->
      <!--upper="3."-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/calf_left_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/calf_left_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/calf_left_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/quad_calf_left_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.41218 0.11044 0"-->
      <!--rpy="3.14159 0 3.43" />-->
    <!--<parent-->
      <!--link="autobed/quad_left_link" />-->
    <!--<child-->
      <!--link="autobed/calf_left_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3."-->
      <!--upper="3."-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/foot_left_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/foot_left_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/foot_left_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/calf_foot_left_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="-0.41279 -0.03188 0"-->
      <!--rpy="0 0 0.09" />-->
    <!--<parent-->
      <!--link="autobed/calf_left_link" />-->
    <!--<child-->
      <!--link="autobed/foot_left_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3."-->
      <!--upper="3."-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/quad_right_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/quad_right_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/quad_right_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/body_quad_right_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.05207 0 0.08636"-->
      <!--rpy="0 0 -.25" />-->
    <!--<parent-->
      <!--link="autobed/lower_body_link" />-->
    <!--<child-->
      <!--link="autobed/quad_right_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/calf_right_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/calf_right_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/calf_right_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/quad_calf_right_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.41218 0.11044 0"-->
      <!--rpy="3.14159 0 3.43" />-->
    <!--<parent-->
      <!--link="autobed/quad_right_link" />-->
    <!--<child-->
      <!--link="autobed/calf_right_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/foot_right_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/foot_right_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/foot_right_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/calf_foot_right_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="-0.41279 -0.03188 0"-->
      <!--rpy="0 0 0.09" />-->
    <!--<parent-->
      <!--link="autobed/calf_right_link" />-->
    <!--<child-->
      <!--link="autobed/foot_right_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/arm_left_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/arm_left_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/arm_left_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/body_arm_left_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.09652 0 -0.17526"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/upper_body_link" />-->
    <!--<child-->
      <!--link="autobed/arm_left_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/forearm_left_rotx_link">-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/arm_forearm_left_rotx_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.28174 -0.0106 -0.04953"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/arm_left_link" />-->
    <!--<child-->
      <!--link="autobed/forearm_left_rotx_link" />-->
    <!--<axis-->
      <!--xyz="1 0 0" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->

  <!--<link-->
    <!--name="autobed/forearm_left_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/forearm_left_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/forearm_left_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/arm_forearm_left_rotz_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0 0 0"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/forearm_left_rotx_link" />-->
    <!--<child-->
      <!--link="autobed/forearm_left_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/hand_left_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/hand_left_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/hand_left_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/forearm_hand_left_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.25146 0 0"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/forearm_left_link" />-->
    <!--<child-->
      <!--link="autobed/hand_left_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/arm_right_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/arm_right_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/arm_right_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/body_arm_right_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.09652 0 0.17526"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/upper_body_link" />-->
    <!--<child-->
      <!--link="autobed/arm_right_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/forearm_right_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/forearm_right_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/forearm_right_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/arm_forearm_right_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.28194 0 0.04953"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/arm_right_link" />-->
    <!--<child-->
      <!--link="autobed/forearm_right_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->
  <!--<link-->
    <!--name="autobed/hand_right_link">-->
    <!--<visual>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/hand_right_link.STL" />-->
      <!--</geometry>-->
      <!--<material-->
        <!--name="">-->
        <!--<color-->
          <!--rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />-->
      <!--</material>-->
    <!--</visual>-->
    <!--<collision>-->
      <!--<origin-->
        <!--xyz="0 0 0"-->
        <!--rpy="0 0 0" />-->
      <!--<geometry>-->
        <!--<mesh-->
          <!--filename="package://hrl_base_selection/urdf/bed_and_environment_mannequin/meshes/hand_right_link.STL" />-->
      <!--</geometry>-->
    <!--</collision>-->
  <!--</link>-->
  <!--<joint-->
    <!--name="autobed/forearm_hand_right_joint"-->
    <!--type="revolute">-->
    <!--<origin-->
      <!--xyz="0.25146 0 0"-->
      <!--rpy="0 0 0" />-->
    <!--<parent-->
      <!--link="autobed/forearm_right_link" />-->
    <!--<child-->
      <!--link="autobed/hand_right_link" />-->
    <!--<axis-->
      <!--xyz="0 0 1" />-->
    <!--<limit-->
      <!--lower="-3"-->
      <!--upper="3"-->
      <!--effort="0"-->
      <!--velocity="0" />-->
  <!--</joint>-->

</robot>