max_obstacle_height:  2.00

footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
#robot_radius: ir_of_robot

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.59
footprint_padding: 0.015
oscillation_timeout: 10.0
oscillation_distance: 0.5
transform_tolerance: 0.2


map_type: voxel
obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.00
  origin_z:             0.0
  z_voxels:             16
  z_resolution:         0.1125
  unknown_cost_value:   0
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  publish_voxel_map: false
  observation_sources:  base_scan #tilt_scan
  base_scan: 
    sensor_frame: base_laser_link
    topic: /base_scan
    data_type: LaserScan
    expected_update_rate: 0.2
    observation_persistence: 0.0 
    marking: true
    clearing: true
    min_obstacle_height: -0.10
    max_obstacle_height: 2.0
 # tilt_scan: 
 #   sensor_frame: laser_tilt_link
 #   topic: /tilt_scan
 #   data_type: LaserScan
 #   expected_update_rate: 0.2
 #   observation_persistence: 0.2
 #   marking: true
 #   clearing: true
 #   min_obstacle_height: -20.00
 #   max_obstacle_height: 40.0}

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.35  # max. distance from an obstacle at which costs are incurred for planning paths.
static_layer:
  enabled:              true
