footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.59
footprint_padding: 0.015
oscillation_timeout: 10.0
oscillation_distance: 0.5

shutdown_costmaps: false

planner_frequency: 1.0
planner_patience: 5.0

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

